In [ ]:
#Ways to Create Numpy arrays


In [2]:
import numpy as np

In [4]:
# 1d array
arra_1d = np.array([1,2,3])
print(arra_1d)

[1 2 3]


In [6]:
# 2D array
arra_2d = np.array([[1,2,3],[4,5,6]])
print(arra_2d)

[[1 2 3]
 [4 5 6]]


In [7]:
# 3D array
arra_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arra_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [12]:
# multiple dimensional arrays inside the array
arra_md = np.array([[[1,2,3],
                      [4,5,6],
                      [7,8,9]],
                    [[10,11,12],
                    [13,14,15],
                    [16,17,18]]])
print(arra_md)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [14]:
#creating array with zeroes
np.zeros(shape=(3,5)) # shape is necessary arg here with first arg as rows and second as columns

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
# creating array with same values in all
np.full(shape=(3,5),fill_value=5) # fill_value will fill up the all values in the indexes


array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [17]:
# sequentially creating array with np.arange
np.arange(start = 1, stop = 9, step = 1) #here start is inclusive and stop is exclusive and step is the amount it jumps from

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
# exampole 2
np.arange(start = 1, stop = 10, step = 2)

array([1, 3, 5, 7, 9])

In [19]:
# anothor way of np.arange
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# creating array with in a definite size but with random values
np.random.randint(low = 0, high = 10, size = (3,5)) # the array will go from 0 to 9 with random values in.

array([[4, 1, 3, 9, 0],
       [7, 4, 8, 6, 2],
       [3, 5, 4, 1, 6]])