In [1]:
import numpy as np

In [4]:
array = np.array([1,2,3])
print(array) #simple array creation

[1 2 3]


In [6]:
array_2d = np.array([[1,2,3],[4,5,6]])
print(array_2d) #a 2d array in the double dic

[[1 2 3]
 [4 5 6]]


In [10]:
type(array_2d) #type of the array

numpy.ndarray

In [21]:
array_misc = np.array([1,'vllms',3])
print(array_misc) # here we see the array is taking all three objects as strings for a single datatype but as we know that string is non definate in size,
                #   as we know numpy only accepts for tjose who have definite bits defined so how?

['1' 'vllms' '3']


In [22]:
array_misc.dtype # here is the answer in the data type as, the U21 limits the size upto 21 string size character so its definite upto 21, so no issue until under this

dtype('<U21')

In [24]:
array_misc[0] = 'really really really longer marshmallow'
print(array_misc) #now here you can see that the longer string got cut since the max size for this array was 21 and there are multiple size like u21, U39 and increase as you create the array they takle the same size of the first array creation.

['really really really ' 'vllms' '3']


In [25]:
# here is example of above explantion
array_big = np.array(['really really really longer marshmallow',2,3])
array_big.dtype # below you can see here is the definite size is 39 .

dtype('<U39')

In [27]:
#difference in an array inside
np.array([[1,2,3,4],[1,2,3]]) #the in dimension should always be the same in multi dimensional matrix/ array

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.